export type ExpandedFairyCatalogBook = {
  title: string;
  slug: string;
  summary: string;
};

export const expandedFairyCatalogBooks: ExpandedFairyCatalogBook[] = [
  { title: "鹅姑娘", slug: "fairy-the-goose-girl", summary: "被侍女夺走身份的公主带着会说话的马头和沉默一起活下去，直到真相终于回到阳光下。" },
  { title: "侏儒怪", slug: "fairy-rumpelstiltskin", summary: "磨坊主的女儿被迫把稻草纺成金子，只能与神秘侏儒做下越来越危险的交换。" },
  { title: "十二个跳舞的公主", slug: "fairy-the-twelve-dancing-princesses", summary: "十二位公主每夜都把舞鞋跳破，通往地下舞会的秘密等待被一个看似普通的士兵发现。" },
  { title: "豌豆公主", slug: "fairy-the-princess-and-the-pea", summary: "一粒小小的豌豆被塞进二十层床垫下，也成了辨认真正公主的奇怪考验。" },
  { title: "打火匣", slug: "fairy-the-tinder-box", summary: "穷士兵得到一只能唤来神奇黑狗的打火匣，从此被卷进欲望、权力与爱情的冒险。" },
  { title: "夜莺", slug: "fairy-the-nightingale", summary: "真正会歌唱的夜莺走进皇宫，也让沉迷华丽玩物的人重新听见生命本来的声音。" },
  { title: "枞树", slug: "fairy-the-fir-tree", summary: "一棵总想着长大和远方的枞树，在愿望实现后才慢慢明白当下曾经拥有的光亮。" },
  { title: "猪倌", slug: "fairy-the-swineherd", summary: "王子化身猪倌接近高傲公主，让真假价值在玩具与真心之间被重新衡量。" },
  { title: "杰克与巨人杀手", slug: "fairy-jack-the-giant-killer", summary: "少年杰克靠胆量和机敏挑战一个又一个巨人，逐步把自己的名字写成传奇。" },
  { title: "太阳东升月亮西落之地", slug: "fairy-east-of-the-sun-and-west-of-the-moon", summary: "少女为了寻回被带往遥远国度的王子，踏上一条比北风更远、比月光更冷的路。" },
  { title: "七只乌鸦", slug: "fairy-the-seven-ravens", summary: "为了救回被诅咒成乌鸦的七个哥哥，小妹妹独自走进月亮、太阳和玻璃山的边界。" },
  { title: "井边的鹅姑娘", slug: "fairy-the-goose-girl-at-the-well", summary: "一个被误解的老姑娘和一位流落的王子在井边相遇，层层伪装后藏着迟来的温柔与身份。" },
  { title: "铁汉斯", slug: "fairy-iron-hans", summary: "被困在铁笼里的野人改变了王子的命运，也让少年在离开宫廷后学会真正的成长。" },
  { title: "红舞鞋", slug: "fairy-the-red-shoes", summary: "一双漂亮的红舞鞋让女孩沉迷虚荣，也把她拖进无法停下的惩罚之舞。" },
  { title: "迪克和他的猫", slug: "fairy-dick-whittington-and-his-cat", summary: "穷孩子带着一只猫闯向城市，希望在陌生世界里为自己挣出一个新开头。" },
  { title: "真正的公主", slug: "fairy-the-real-princess", summary: "一位在暴风雨夜敲门的少女，用整夜无法安睡证明了自己真正的公主身份。" },
  { title: "小精灵和鞋匠", slug: "fairy-the-elves-and-the-shoemaker", summary: "穷鞋匠在绝望中留下半成品，第二天却发现夜里有人替他把鞋做得完美无比。" },
  { title: "金鸟", slug: "fairy-the-golden-bird", summary: "为了追寻偷走金苹果的金鸟，最不起眼的小儿子一路遇见狐狸、金马与被囚的公主。" },
  { title: "幸运的汉斯", slug: "fairy-hans-in-luck", summary: "捧着大块银子回家的汉斯一路交换，看似越来越穷，却觉得自己越来越轻松。" },
  { title: "约琳德和约林格尔", slug: "fairy-jorinda-and-jorindel", summary: "恋人被女巫拆散后，青年为了救回被变成小鸟的姑娘，必须学会对抗黑暗魔法。" },
  { title: "老苏丹", slug: "fairy-old-sultan", summary: "年迈的狗即将被主人抛弃时，仍想办法证明自己的忠诚与价值。" },
  { title: "稻草、煤块和豆子", slug: "fairy-the-straw-the-coal-and-the-bean", summary: "三个从厨房里逃出来的小东西一起上路，却在过河时把命运闹成一场荒唐意外。" },
  { title: "狗和麻雀", slug: "fairy-the-dog-and-the-sparrow", summary: "被辜负的狗与替它出头的麻雀，让一个冷酷车夫一步步走向自取其祸的结局。" },
  { title: "柳鹪鹩和熊", slug: "fairy-the-willow-wren-and-the-bear", summary: "一只小鸟与大熊起了争执，小小的翅膀也能让庞然大物尝到失败滋味。" },
  { title: "猫和老鼠合伙", slug: "fairy-cat-and-mouse-in-partnership", summary: "猫和老鼠约好一起存冬粮，可真正靠近食物时，友情很快暴露出偏斜的一面。" },
  { title: "鸡先生和鸡太太历险记", slug: "fairy-the-adventures-of-chanticleer-and-partlet", summary: "一对鸡夫妇出门找坚果吃，却在一连串小灾祸里把轻快旅程变得越来越混乱。" },
  { title: "芬杜鸟", slug: "fairy-fundevogel", summary: "两个孩子从女巫手中逃走，靠抛出梳子、镜子和语言一次次改写被追上的命运。" },
  { title: "老鼠、小鸟和香肠", slug: "fairy-the-mouse-the-bird-and-the-sausage", summary: "原本分工和谐的三个伙伴，因为羡慕彼此的角色而把平静日子推向失衡。" },
  { title: "霍勒大妈", slug: "fairy-mother-holle", summary: "勤快女孩跌入井里来到雪婆婆的世界，也因此得到金雨般的回报。" },
  { title: "强盗新郎", slug: "fairy-the-robber-bridegroom", summary: "被安排出嫁的姑娘误闯未婚夫的森林屋，眼前出现的却是一场血腥而真实的危险。" },
  { title: "小拇指", slug: "fairy-tom-thumb", summary: "只有拇指大小的小男孩在牛肚、狼嘴和陌生人手里辗转，却总能用机灵找到回家的路。" },
  { title: "聪明的格蕾特", slug: "fairy-clever-gretel", summary: "自作聪明的女仆一边偷吃烤鸡，一边还想把一切都说成别人犯下的错。" },
  { title: "小农夫", slug: "fairy-the-little-peasant", summary: "身材矮小的农夫接连骗过有钱邻居和法官，让弱小也能在不公平里找到翻盘机会。" },
  { title: "弗雷德里克和凯瑟琳", slug: "fairy-frederick-and-catherine", summary: "一对笨拙夫妻把日常生活过成连环误会，也让每一次自作主张都显得格外好笑。" },
  { title: "甜心罗兰", slug: "fairy-sweetheart-roland", summary: "少女和恋人为躲避女巫追杀一路变形逃亡，爱情也在风声鹤唳中被不断试炼。" },
  { title: "石竹花", slug: "fairy-the-pink", summary: "一朵神奇的石竹牵引出愿望、离别与重逢，让命运在几次擦身而过后终于合拢。" },
  { title: "聪明的艾尔莎", slug: "fairy-clever-elsie", summary: "总把最坏结果先想完的艾尔莎，把一顿饭和一桩婚事都推成了荒诞笑谈。" },
  { title: "白蛇", slug: "fairy-the-white-snake", summary: "年轻仆人尝到白蛇后忽然听懂万物语言，也由此走上一连串不可能的任务。" },
  { title: "蜂王", slug: "fairy-the-queen-bee", summary: "三个王子面对石头王国的试炼时，最善待小生命的那个反而赢得了最后的答案。" },
  { title: "杜松树", slug: "fairy-the-juniper-tree", summary: "在继母的恶意与鸟儿的歌声之间，一个被害死的孩子以极其诡异的方式回到人间。" },
  { title: "聪明的汉斯", slug: "fairy-clever-hans", summary: "总以为自己做得很对的汉斯，把恋爱与办事都弄成了一连串让人哭笑不得的偏差。" },
  { title: "三种语言", slug: "fairy-the-three-languages", summary: "被父亲送去学本事的少年最后只学会狗叫、鸟鸣和青蛙声，却因此走向意外的命运。" },
  { title: "四个聪明的兄弟", slug: "fairy-the-four-clever-brothers", summary: "四兄弟各自学成一门绝技，最终必须把这些本事拼在一起才能救回公主。" },
  { title: "百合花与狮子", slug: "fairy-lily-and-the-lion", summary: "公主为了爱情和承诺经历分离、诅咒与流浪，直到人与兽的边界再次被爱打破。" },
  { title: "狐狸和马", slug: "fairy-the-fox-and-the-horse", summary: "被主人抛弃的老马遇见狐狸，在一场虚张声势里重新换回了生存机会。" },
  { title: "蓝灯", slug: "fairy-the-blue-light", summary: "被背叛的士兵在深井里捡到蓝灯，也因此召来一个能替他完成复仇与爱情的精灵。" },
  { title: "乌鸦公主", slug: "fairy-the-raven", summary: "少年为解开乌鸦公主的诅咒踏上旅途，却总在最后一步被自己的犹豫绊住。" },
  { title: "生命之水", slug: "fairy-the-water-of-life", summary: "为了救活病重国王，最小的王子踏上寻找生命之水的路，也在途中认清兄长的背叛。" },
  { title: "十二个猎人", slug: "fairy-the-twelve-huntsmen", summary: "失去王子婚约的公主女扮男装混进宫廷，用沉默与忠诚等待被重新认出。" },
  { title: "金山国王", slug: "fairy-the-king-of-the-golden-mountain", summary: "穷人用与恶魔立下的约换来财富，后来却必须穿过层层变形与背叛去把幸福夺回来。" },
  { title: "万事通博士", slug: "fairy-doctor-knowall", summary: "一个其实并不懂医术的人靠着巧合和气势，硬是让自己成了人人敬畏的神医。" },
  { title: "狐狸太太的婚事", slug: "fairy-the-wedding-of-mrs-fox", summary: "狐狸太太在丈夫生死未卜时忙着挑选新郎，也让一场婚事变得既刻薄又滑稽。" },
  { title: "魔法生菜", slug: "fairy-the-salad", summary: "一颗看似普通的生菜和一只魔法鸟把贪心的公主与王子推入一连串身份倒转。" },
  { title: "学会害怕的人", slug: "fairy-the-youth-who-went-forth-to-learn-what-fear-was", summary: "一个从不会害怕的年轻人四处寻找恐惧，结果在鬼怪、黑夜和婚姻里一路误打误撞。" },
  { title: "画眉嘴国王", slug: "fairy-king-thrushbeard", summary: "傲慢公主嘲笑所有求婚者后被迫下嫁穷汉，漫长的困窘最终让她看见自己的偏狭。" },
  { title: "猫皮姑娘", slug: "fairy-cat-skin", summary: "公主披上猫皮逃离不该存在的婚约，在灰尘与厨房里把尊严与真身份一起藏起。" },
  { title: "忠实的约翰", slug: "fairy-faithful-john", summary: "老仆人为保护年轻国王不惜一次次背负误解，忠诚也因此走到几乎无法回头的地方。" },
  { title: "兄妹俩", slug: "fairy-brother-and-sister", summary: "逃离恶毒继母的兄妹在森林里相依为命，却因一道魔法泉水被迫换了新的生存方式。" },
  { title: "林中的三个小矮人", slug: "fairy-the-three-little-men-in-the-wood", summary: "善良女孩在雪地里遇见三位小矮人并得到祝福，而恶毒继姐只换来相反的命运。" },
  { title: "三个纺纱女", slug: "fairy-the-three-spinning-women", summary: "懒得纺纱的姑娘在三位奇怪老妇帮助下脱困，也因此意外嫁给了王子。" },
  { title: "魔鬼的三根金发", slug: "fairy-the-devil-with-the-three-golden-hairs", summary: "被预言会娶公主的穷孩子被层层陷害，最后却真的从魔鬼头上带回了三根金发。" },
  { title: "没有手的姑娘", slug: "fairy-the-girl-without-hands", summary: "为了摆脱与魔鬼的交易，一个年轻姑娘失去双手，却仍在流亡中守住了善良与希望。" },
  { title: "小桌子、金驴和棍子", slug: "fairy-the-magic-table-the-gold-donkey-and-the-club-in-the-sack", summary: "三兄弟各自得到魔法宝物，又必须把被骗子骗走的一切再亲手夺回来。" },
  { title: "熊皮人", slug: "fairy-bearskin", summary: "士兵与魔鬼订下七年契约，披着熊皮在污秽中活下去，只为换一个重新被爱的人生。" },
  { title: "星星银币", slug: "fairy-star-money", summary: "一无所有的小女孩把最后一点东西都分给别人，夜空却把银币和新衣服一并落向她。" },
  { title: "雪白和玫瑰红", slug: "fairy-snow-white-and-rose-red", summary: "两姐妹在冬夜收留一只熊，也慢慢被带进一个矮人守着的诅咒秘密。" },
  { title: "月亮", slug: "fairy-the-moon", summary: "几个男人偷走别人国度里的月亮带回故乡，也让死后的世界第一次有了银白色的光。" },
  { title: "玛琳公主", slug: "fairy-maid-maleen", summary: "被高塔囚禁多年的公主在乱世里流落为厨房女仆，最终仍一步步走回自己的位置。" },
  { title: "玻璃棺材", slug: "fairy-the-glass-coffin", summary: "裁缝误入山中宫殿，在玻璃棺与鹿角男仆之间撞见一场被封存多年的魔法真相。" },
  { title: "一只眼、两只眼和三只眼", slug: "fairy-one-eye-two-eyes-and-three-eyes", summary: "最普通的二眼女孩在家中受尽轻视，却靠一只神奇山羊让命运慢慢转向。" },
  { title: "小毛驴", slug: "fairy-the-little-donkey", summary: "王后生下的小毛驴其实是被魔法捉弄的王子，只有穿过羞辱与离家后才有机会改变样子。" },
  { title: "森林里的小屋", slug: "fairy-the-hut-in-the-forest", summary: "善良少女在森林深处照顾陌生老人和动物，也因此解开了一座被诅咒的屋子。" },
  { title: "汉斯我的刺猬", slug: "fairy-hans-my-hedgehog", summary: "半人半刺猬的孩子骑着公鸡四处流浪，在被嫌弃的人生里一点点争回自己的尊严。" },
];

export const expandedFairyCatalogBySlug = new Map(expandedFairyCatalogBooks.map((book) => [book.slug, book]));
