BEGIN;

WITH book_seed(category_key, title, slug, summary) AS (
  VALUES
    ('fairy_tale', '小红帽', 'fairy-little-red-riding-hood', '一个戴红斗篷的小女孩穿过森林去看外婆，却在路上遇见了危险的狼。'),
    ('fairy_tale', '白雪公主', 'fairy-snow-white', '被王后嫉妒的白雪公主逃入森林，在七个小矮人的木屋里暂时找到庇护。'),
    ('fairy_tale', '灰姑娘', 'fairy-cinderella', '被苛待的灰姑娘在魔法帮助下参加舞会，并留下改变命运的玻璃鞋。'),
    ('fairy_tale', '睡美人', 'fairy-sleeping-beauty', '被诅咒的公主沉睡多年，整个王国也随她一起停在漫长的梦里。'),
    ('fairy_tale', '莴苣姑娘', 'fairy-rapunzel', '长发少女被困在高塔之中，等待命运与自由从窗边垂下。'),
    ('fairy_tale', '汉塞尔与格蕾特', 'fairy-hansel-and-gretel', '一对兄妹被丢进森林，在糖果屋里遇见了真正的危险。'),
    ('fairy_tale', '青蛙王子', 'fairy-frog-prince', '任性的公主与一只会说话的青蛙达成约定，隐藏的身份随之浮现。'),
    ('fairy_tale', '穿靴子的猫', 'fairy-puss-in-boots', '一只聪明的猫用机敏和计策帮助主人逆转贫穷的命运。'),
    ('fairy_tale', '不来梅的音乐家', 'fairy-bremen-town-musicians', '四只年老的动物离开旧主人，决定一起去寻找新的生活。'),
    ('fairy_tale', '勇敢的小裁缝', 'fairy-the-valiant-little-tailor', '一个小裁缝因一句夸张口号被卷入巨人、国王与公主的考验。'),
    ('fairy_tale', '金鹅', 'fairy-the-golden-goose', '一只神奇的金鹅让贪心的人们一个接一个黏在一起，也带来意外好运。'),
    ('fairy_tale', '十二兄弟', 'fairy-the-twelve-brothers', '被命运驱赶的十二个王子与突然到来的妹妹重新连上彼此的人生。'),
    ('fairy_tale', '六只天鹅', 'fairy-the-six-swans', '一位公主为了救回被施咒的兄长们，必须在沉默中完成艰难的任务。'),
    ('fairy_tale', '渔夫和金鱼', 'fairy-the-fisherman-and-the-goldfish', '一次善意的放生引出无穷无尽的贪欲，海浪也随之越来越高。'),
    ('fairy_tale', '海的女儿', 'fairy-the-little-mermaid', '一位人鱼公主为爱离开海底世界，却不得不面对无法说出口的代价。'),
    ('fairy_tale', '野天鹅', 'fairy-the-wild-swans', '流亡的公主追寻变成天鹅的兄长，在荆棘与沉默中守住亲情。'),
    ('fairy_tale', '丑小鸭', 'fairy-the-ugly-duckling', '被误解和排斥的小鸭一路漂泊，最终发现真正的自己。'),
    ('fairy_tale', '卖火柴的小女孩', 'fairy-the-little-match-girl', '寒夜里卖火柴的小女孩在短暂的火光中看见温暖与幻象。'),
    ('fairy_tale', '皇帝的新装', 'fairy-the-emperors-new-clothes', '整个王国都在配合一场荒唐骗局，直到孩子说出所有人不敢说的话。'),
    ('fairy_tale', '拇指姑娘', 'fairy-thumbelina', '一个拇指大小的女孩被不断带离原地，在陌生世界中寻找归宿。'),
    ('fairy_tale', '坚定的锡兵', 'fairy-the-steadfast-tin-soldier', '只有一条腿的锡兵在风浪与火焰之间守住自己唯一的爱慕。'),
    ('fairy_tale', '雪女王', 'fairy-the-snow-queen', '一个被冰镜碎片改变的男孩被雪女王带走，女孩踏上漫长的寻找之路。'),
    ('fairy_tale', '美女与野兽', 'fairy-beauty-and-the-beast', '少女为了父亲住进野兽的城堡，并在相处中重新理解外表与真心。'),
    ('fairy_tale', '蓝胡子', 'fairy-bluebeard', '新婚妻子被告诫不要打开某一扇门，而门后的秘密远比她想象得可怕。'),
    ('fairy_tale', '杰克和魔豆', 'fairy-jack-and-the-beanstalk', '一把豆子长成通天藤蔓，贫穷少年因此闯入巨人的天空王国。'),
    ('fairy_tale', '金发姑娘和三只熊', 'fairy-goldilocks-and-the-three-bears', '误闯森林小屋的女孩在别人的世界里挑选最适合自己的东西。'),
    ('fairy_tale', '三只小猪', 'fairy-the-three-little-pigs', '三只小猪各自盖房子，而狼的到来很快考验了它们的选择。'),
    ('fairy_tale', '狼和七只小山羊', 'fairy-the-wolf-and-the-seven-kids', '趁母羊不在家时，伪装成善意来访者的狼敲响了门。'),
    ('fairy_tale', '狐狸和猫', 'fairy-the-fox-and-the-cat', '自夸有许多办法的狐狸遇见危险时，未必比只有一种办法的猫更从容。'),
    ('fairy_tale', '姜饼人', 'fairy-the-gingerbread-man', '一个会跑会说话的姜饼人一路逃离追赶，却忽略了最后的诱惑。'),
    ('fairy_tale', '阿里巴巴和四十大盗', 'fairy-ali-baba-and-the-forty-thieves', '樵夫意外发现强盗宝藏，也从此卷入一连串贪婪与机智的较量。'),
    ('fairy_tale', '阿拉丁和神灯', 'fairy-aladdin-and-the-magic-lamp', '一个贫寒少年获得神灯，从此在欲望、谎言与奇迹之间前行。'),
    ('fairy_tale', '十二个月', 'fairy-the-twelve-months', '在雪地里被逼着寻找春天花朵的女孩，遇见了掌管季节的神秘力量。'),

    ('fable', '乌鸦和狐狸', 'fable-the-crow-and-the-fox', '狐狸用恭维诱使乌鸦张口，掉下到手的食物。'),
    ('fable', '龟兔赛跑', 'fable-the-tortoise-and-the-hare', '自信过头的兔子在比赛中偷懒，缓慢但稳定的乌龟最终赢得胜利。'),
    ('fable', '狼来了', 'fable-the-boy-who-cried-wolf', '一再说谎的孩子在真正遇到狼时失去了所有人的信任。'),
    ('fable', '北风和太阳', 'fable-the-north-wind-and-the-sun', '北风与太阳比试谁能让旅人脱下外衣，力量与温暖因此被重新比较。'),
    ('fable', '狮子和老鼠', 'fable-the-lion-and-the-mouse', '强大的狮子放过了弱小的老鼠，而后者在意想不到的时候回报了恩情。'),
    ('fable', '蚂蚁和蚱蜢', 'fable-the-ant-and-the-grasshopper', '勤劳储粮的蚂蚁与只顾歌唱的蚱蜢，在冬天迎来截然不同的结果。'),
    ('fable', '农夫和蛇', 'fable-the-farmer-and-the-viper', '出于怜悯救下冻僵的蛇，反而让善意被反咬一口。'),
    ('fable', '下金蛋的鹅', 'fable-the-goose-that-laid-the-golden-eggs', '因贪念而急于一次拿走全部财富的人，往往会失去原本拥有的一切。'),
    ('fable', '城里老鼠和乡下老鼠', 'fable-the-town-mouse-and-the-country-mouse', '丰盛与安稳之间，两只老鼠对生活有了不同的选择。'),
    ('fable', '狼和小羊', 'fable-the-wolf-and-the-lamb', '当强者决意加害时，再清楚的辩解也可能毫无作用。'),
    ('fable', '狐狸和葡萄', 'fable-the-fox-and-the-grapes', '得不到的葡萄被说成酸的，一句自我安慰说尽人的心思。'),
    ('fable', '乌鸦喝水', 'fable-the-thirsty-crow', '口渴的乌鸦用小石子让瓶中水位升高，靠耐心解决了难题。'),
    ('fable', '井底之蛙', 'fable-the-frog-in-the-well', '只见过井口天空的青蛙，很难理解真正辽阔的世界。'),
    ('fable', '守株待兔', 'fable-waiting-by-a-tree-stump', '偶然得利之后一味守候的人，往往再也等不到相同的运气。'),
    ('fable', '刻舟求剑', 'fable-carving-a-mark-on-the-boat', '方法停在原地，世界却已经变了，错位的坚持只会离目标更远。'),
    ('fable', '掩耳盗铃', 'fable-covering-ones-ears-while-stealing-a-bell', '骗过自己并不等于骗过别人，荒唐往往始于自欺。'),
    ('fable', '滥竽充数', 'fable-filling-out-the-ranks', '混在人群里装会吹竽的人，一旦单独考验便无所遁形。'),
    ('fable', '画蛇添足', 'fable-drawing-legs-on-a-snake', '本已完成的事情因多余的一笔而前功尽弃。'),
    ('fable', '自相矛盾', 'fable-self-contradiction', '同时夸耀最锋利的矛和最坚固的盾，最终让谎言彼此碰撞。'),
    ('fable', '买椟还珠', 'fable-returning-the-pearl-and-keeping-the-box', '只顾华丽外表而忽视真正价值的人，容易做出荒唐选择。'),
    ('fable', '郑人买履', 'fable-the-man-of-zheng-buys-shoes', '比起脚的真实尺寸，他更相信手里那张失效的尺码。'),
    ('fable', '亡羊补牢', 'fable-mend-the-fold-after-losing-sheep', '损失发生后及时补救，仍然比一错到底要好。'),
    ('fable', '南辕北辙', 'fable-heading-north-by-driving-south', '方向错了，再努力也只会离目的地越来越远。'),
    ('fable', '杯弓蛇影', 'fable-taking-the-bow-in-the-cup-for-a-snake', '被自己的恐惧放大的幻象，会让人把影子当成真相。'),
    ('fable', '狐假虎威', 'fable-the-fox-borrowing-the-tigers-might', '借来的威势虽然一时有效，却遮不住本来的虚弱。'),
    ('fable', '黔驴技穷', 'fable-the-guizhou-donkey-has-exhausted-its-tricks', '当所有招数都被看穿后，虚张声势就再也无法保护自己。'),
    ('fable', '鹬蚌相争', 'fable-the-snipe-and-the-clam', '争执不下的双方彼此僵持，最终让旁观者轻松得利。'),
    ('fable', '塞翁失马', 'fable-the-old-frontier-man-loses-his-horse', '看似坏事的开端也许会转成好事，福祸并不总能立刻分明。'),
    ('fable', '惊弓之鸟', 'fable-the-bird-startled-by-the-bow', '受过伤的鸟只是听见弓弦声，便已先一步被恐惧击中。'),
    ('fable', '螳臂当车', 'fable-the-mantis-trying-to-stop-a-chariot', '不顾力量差距的硬碰硬，往往会把勇敢变成徒劳。'),
    ('fable', '叶公好龙', 'fable-lord-ye-loves-dragons', '嘴上热爱的事物一旦真实出现，未必还能被真正接受。'),
    ('fable', '东施效颦', 'fable-dongshi-imitates-xishi', '不理解缘由就模仿外表，往往只会放大自己的不合时宜。'),
    ('fable', '愚公移山', 'fable-the-foolish-old-man-who-moved-the-mountains', '看似不可能完成的事，在坚定与传承中也可能慢慢动摇山岳。'),

    ('mythology', '普罗米修斯盗火', 'myth-prometheus-steals-fire', '普罗米修斯把火带给人类，也因此遭受众神的长久惩罚。'),
    ('mythology', '潘多拉的盒子', 'myth-pandoras-box', '一个被禁止打开的盒子一旦被掀开，灾难和希望便同时流向人间。'),
    ('mythology', '珀耳塞福涅与四季', 'myth-persephone-and-the-seasons', '少女被带往冥界之后，母亲的悲伤让大地开始有了四季更替。'),
    ('mythology', '代达罗斯与伊卡洛斯', 'myth-daedalus-and-icarus', '父子借羽翼逃离囚禁，而过于靠近太阳的代价格外沉重。'),
    ('mythology', '珀尔修斯与美杜莎', 'myth-perseus-and-medusa', '年轻英雄踏上危险旅程，试图斩下会让人石化的蛇发女妖之首。'),
    ('mythology', '忒修斯与米诺陶洛斯', 'myth-theseus-and-the-minotaur', '在迷宫深处等待他的不只是怪物，还有选择回头的那根线。'),
    ('mythology', '阿喀琉斯之踵', 'myth-achilles-heel', '最强战士也有唯一无法遮蔽的弱点，而战争总会逼近那里。'),
    ('mythology', '奥德修斯与独眼巨人', 'myth-odysseus-and-the-cyclops', '机智的航海者被困在独眼巨人的洞穴里，只能靠谎言和耐心脱身。'),
    ('mythology', '奥菲欧与欧律狄刻', 'myth-orpheus-and-eurydice', '为了挽回爱人，乐师走进冥界，却在最后一刻败给回头的一眼。'),
    ('mythology', '赫拉克勒斯的十二试炼', 'myth-heracles-twelve-labours', '为了赎罪，英雄必须完成一系列几乎不可能的任务。'),
    ('mythology', '阿波罗与达芙妮', 'myth-apollo-and-daphne', '被追逐的达芙妮在绝望中化作月桂，留下爱与失去的象征。'),
    ('mythology', '厄洛斯与普绪克', 'myth-eros-and-psyche', '爱神与凡人少女的相遇，让信任、嫉妒与试炼交织成命运。'),
    ('mythology', '法厄同驾太阳车', 'myth-phaethon-and-the-chariot-of-the-sun', '少年试图证明自己，却在无法驾驭的神力前将世界推向失控。'),
    ('mythology', '德墨忒耳寻找女儿', 'myth-demeter-searches-for-her-daughter', '丰饶女神踏遍人间寻找失去的女儿，土地也随她的悲伤荒芜。'),
    ('mythology', '阿塔兰忒与金苹果', 'myth-atalanta-and-the-golden-apples', '奔跑无人能及的阿塔兰忒，最终在爱情与胜负之间被金苹果分神。'),
    ('mythology', '特洛伊木马', 'myth-the-trojan-horse', '一件看似退场的礼物被推进城门，也把毁灭带进了特洛伊。'),
    ('mythology', '女娲补天', 'myth-nuwa-mends-the-sky', '天地破裂、洪水四起之时，女娲炼石补天以重整世界。'),
    ('mythology', '后羿射日', 'myth-houyi-shoots-down-the-suns', '十日并出炙烤大地，后羿以神箭为人间留下一轮可承受的太阳。'),
    ('mythology', '嫦娥奔月', 'myth-change-flies-to-the-moon', '不死药、离别与月宫，让一段人间关系被永远拉向天上。'),
    ('mythology', '夸父逐日', 'myth-kuafu-chases-the-sun', '巨人追逐太阳直到力竭倒下，却把执念变成山川与树林。'),
    ('mythology', '精卫填海', 'myth-jingwei-fills-the-sea', '小鸟衔来木石，一次次投向大海，像在与命运本身对抗。'),
    ('mythology', '哪吒闹海', 'myth-nezha-stirs-up-the-sea', '少年哪吒与龙宫冲突，掀起关于反抗、代价与重生的故事。'),
    ('mythology', '盘古开天', 'myth-pangu-separates-heaven-and-earth', '混沌被劈开后，盘古以身躯撑起天地，也让世界真正成形。'),
    ('mythology', '牛郎织女', 'myth-the-cowherd-and-the-weaver-girl', '相爱的两人被银河分隔，只能在一年一度的鹊桥上重逢。'),
    ('mythology', '大禹治水', 'myth-yu-controls-the-flood', '与洪水缠斗多年之后，大禹用疏导而非封堵改变了人间。'),
    ('mythology', '刑天舞干戚', 'myth-xingtian-defies-heaven', '即使失去头颅，刑天仍挥舞武器，像永不屈服的意志本身。'),
    ('mythology', '共工怒触不周山', 'myth-gonggong-crashes-into-buzhou-mountain', '愤怒的神撞断天柱，天倾地斜，世界秩序也从此改变。'),
    ('mythology', '仓颉造字', 'myth-cangjie-invents-writing', '当文字被创造出来，人与天地万物之间也多了一种新的连接。'),
    ('mythology', '神农尝百草', 'myth-shennong-tastes-hundreds-of-herbs', '为了找到救人的药草，神农一次次亲自试毒，替众人探路。'),
    ('mythology', '黄帝战蚩尤', 'myth-the-yellow-emperor-battles-chiyou', '迷雾与战争笼罩大地，黄帝与蚩尤之战决定了部族的新秩序。'),
    ('mythology', '奥丁求取卢恩', 'myth-odin-seeks-the-runes', '为了获得智慧与符文，奥丁把自己悬挂在世界树上直面痛苦。'),
    ('mythology', '雷神之锤失窃', 'myth-thors-hammer-is-stolen', '雷神失去象征力量的锤子后，只能用荒诞伪装去把它夺回来。'),
    ('mythology', '芬里尔与诸神黄昏', 'myth-fenrir-and-ragnarok', '被束缚的巨狼终将在末日挣脱，众神也将迎来预言中的终局。')
)
INSERT INTO story_books (
  category_id,
  title,
  slug,
  cover_image,
  summary,
  key_scenes,
  original_synopsis,
  public_domain,
  is_active
)
SELECT
  c.id,
  s.title,
  s.slug,
  NULL,
  s.summary,
  '[]'::jsonb,
  s.summary,
  TRUE,
  TRUE
FROM book_seed s
JOIN story_categories c ON c.key = s.category_key
ON CONFLICT (slug) DO UPDATE
SET
  category_id = EXCLUDED.category_id,
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  original_synopsis = EXCLUDED.original_synopsis,
  public_domain = EXCLUDED.public_domain,
  is_active = EXCLUDED.is_active,
  updated_at = NOW();

COMMIT;
